"""Fix stage and rezume relationships

Revision ID: 52826d7940fe
Revises: 69511a9bf524
Create Date: 2024-12-02 00:29:00.120597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52826d7940fe'
down_revision: Union[str, None] = '69511a9bf524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rezumes', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rezumes', 'stages', ['stage_id'], ['id'])
    op.drop_constraint('stages_rezume_id_fkey', 'stages', type_='foreignkey')
    op.drop_column('stages', 'rezume_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('rezume_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stages_rezume_id_fkey', 'stages', 'rezumes', ['rezume_id'], ['id'])
    op.drop_constraint(None, 'rezumes', type_='foreignkey')
    op.drop_column('rezumes', 'stage_id')
    # ### end Alembic commands ###
